### PR TITLE
Emoji chat

### LINKED ISSUE #63: Emoji Chat

### PR DESCRIPTION
**Pull request by M1NN**
closes #63 

Add the ability to have the person controlling a game send emojis to the people playing
NOTE: UI could use some work but that can be done when we update the play view UI as a whole

teacher_view
student_view
|--|--|

### CODE REVIEW

**Review by bushw011 — DISMISSED** [review]
Works well. I didn't find any bugs.

**Review by EthanUphoff — DISMISSED** [review]
Looks good to me

**Review by EthanUphoff — DISMISSED** [review]
Looks good to me

**Review by EthanUphoff — APPROVED** [review]
Nice fix

**Pull request merged**
